name: Docker Image CI to Azure

on:
  push:
    branches: [ "main" ]

env:
    AZURE_USERNAME: yernoor
    AZURE_FRONTEND_NAME: yernoorfrontend
    AZURE_BACKEND_NAME: yernoorbackend
    AZURE_FRONTEND_IP_PUBLIC: 172.190.169.106
    AZURE_BACKEND_IP_PUBLIC: 172.190.169.95

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy Backend to Azure Backend VM
      run: scp -r backend/* yernoor@${{ env.AZURE_BACKEND_IP_PUBLIC }}:/backend
    
    - name: Run postgres on Azure Backend VM
      run: docker run -d --name db -e POSTGRES_DB=hackathon -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5433:5432 postgres
      
    - name: Start Backend on Azure Backend VM
      run: ssh yernoor@${{ env.AZURE_BACKEND_IP_PUBLIC }} "docker build -t backend /backend && docker run -d -p 5000:5000 backend"

    - name: Show Container IP
      run: ssh yernoor@${{ env.AZURE_BACKEND_IP_PUBLIC }} "docker ps -a"

    - name: Copy Frontend to Azure Frontend VM
      run: scp -r frontend/* yernoor@${{ env.AZURE_FRONTEND_IP_PUBLIC }}:/frontend

    - name: Start Frontend on Azure Frontend VM
      run: ssh yernoor@${{ env.AZURE_FRONTEND_IP_PUBLIC }} "docker build -t frontend /frontend && docker run -d -p 3000:3000 frontend"

