name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Frontend
      run: docker build -t frontend ./client

    - name: Build Backend
      run: docker build -t backend ./server

    - name: Publish Locally
      run: docker-compose up -d
