name: Docker Image CI to Azure

on:
  push:
    branches: [ "main" ]

env:
    AZURE_USERNAME: yernoor
    AZURE_FRONTEND_NAME: yernoorfrontend
    AZURE_BACKEND_NAME: yernoorbackend
    AZURE_FRONTEND_IP_PUBLIC: 172.190.169.106
    AZURE_BACKEND_IP_PUBLIC: 172.190.169.95

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install ssh keys
      run: install -m 600 -D /dev/null ~/.ssh/id_rsa

    - name: ssh private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

    - name: add to known hosts
      run: ssh-keyscan -p 22 -H ${{ env.AZURE_FRONTEND_IP_PUBLIC }}  > ~/.ssh/known_hosts

    - name: add to known hosts
      run: ssh-keyscan -p 22 -H ${{ env.AZURE_BACKEND_IP_PUBLIC }}  > ~/.ssh/known_hosts

    
    - name: Login to Azure Backend VM
      uses: appleboy/ssh-action@v1.0.3
      with: 
        host: ${{ env.AZURE_BACKEND_IP_PUBLIC }}
        username: yernoor
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Login to Azure Frontend VM
      uses: appleboy/ssh-action@v1.0.3
      with: 
        host: ${{ env.AZURE_FRONTEND_IP_PUBLIC }}
        username: yernoor
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Backend to Azure Backend VM
      run: sshpass -p 'Singularity2022!' scp -r backend/* yernoor@${{ env.AZURE_BACKEND_IP_PUBLIC }}:/backend
    
    - name: Run postgres on Azure Backend VM
      run: sshpass -p 'Singularity2022!' ssh yernoor@${{ env.AZURE_BACKEND_IP_PUBLIC }} "docker run -d --name db -e POSTGRES_DB=hackathon -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5433:5432 postgres"
      
    - name: Start Backend on Azure Backend VM
      run: sshpass -p 'Singularity2022!' ssh yernoor@${{ env.AZURE_BACKEND_IP_PUBLIC }} "docker build -t backend /backend && docker run -d -p 5000:5000 backend"

    - name: Show Container IP
      run: sshpass -p 'Singularity2022!' ssh yernoor@${{ env.AZURE_BACKEND_IP_PUBLIC }} "docker ps -a"

    - name: Copy Frontend to Azure Frontend VM
      run: sshpass -p 'Singularity2022!' scp -r frontend/* yernoor@${{ env.AZURE_FRONTEND_IP_PUBLIC }}:/frontend

    - name: Start Frontend on Azure Frontend VM
      run: sshpass -p 'Singularity2022!' ssh yernoor@${{ env.AZURE_FRONTEND_IP_PUBLIC }} "docker build -t frontend /frontend && docker run -d -p 3000:3000 frontend"

